name: ddd_notes
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^0.6.9
  cloud_firestore: ^0.14.3
  dartz: ^0.9.2
  firebase_auth: ^0.18.3
  firebase_core: ^0.5.2
  flushbar: ^1.10.4
  flutter_bloc: ^6.1.1
  flutter_hooks: ^0.15.0
  flutter_slidable: ^0.5.7
  freezed_annotation: ^0.12.0
  get_it: ^5.0.1
  google_sign_in: ^4.5.6
  implicitly_animated_reorderable_list: ^0.3.2
  injectable: ^1.0.5
  json_annotation: ^3.1.0
  kt_dart: ^0.8.0
  provider: ^4.3.2+2
  rxdart: ^0.24.1
  uuid: ^2.2.2

dev_dependencies:
  auto_route_generator: ^0.6.10
  build_runner: 1.10.6
  freezed: ^0.12.2
  injectable_generator: ^1.0.6
  json_serializable: ^3.5.0
  lint: ^1.3.1

flutter:
  uses-material-design: true
